# Site settings
title: Стихи из Библии
email: gilnator@gmail.com
description: Мини-сайт для просмотра любимых стихов из Библии.
url: "http://127.0.0.1:4000" # the base hostname & protocol for your site
#url: "http://prostodemon.github.io/bible-verse" # the base hostname & protocol for your site
paginate: 1

vk_author_link: http://vk.com/iganin
github_username:  prostodemon

# Build settings
markdown: kramdown

tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty